# docker-compose.prod.yml
services:

  om-mysql-db:
    image: mysql:8.0
    container_name: om-distribution-mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - om_internal_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  om-backend:
    image: ghcr.io/marinm80/om_distribution-backend:latest
    container_name: om-distribution-backend
    restart: unless-stopped
    depends_on:
      om-mysql-db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@om-mysql-db:3306/${MYSQL_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      PORT: 5000
      NODE_ENV: production
    volumes:
      - uploads_data:/app/public/uploads
    networks:
      - coolify
      - om_internal_net

  om-frontend:
    image: ghcr.io/marinm80/om_distribution-frontend:latest
    container_name: om-distribution-frontend
    restart: unless-stopped
    depends_on:
      - om-backend
    networks:
      - coolify

networks:
  coolify:
    external: true
  om_internal_net:
    driver: bridge

volumes:
  mysql_data:
  uploads_data: